# Project Configuration
project.name=Adbrowser
project.url=https://github.com/BetterAndroid/Adbrowser
project.description=A modern cross-platform Android file manager powered by ADB.
project.copyright=Copyright (C) 2019-present HighCapable. All rights reserved.
project.groupName=com.highcapable.adbrowser
project.version="0.0.1"
project.app.version=${project.version}
project.core.common.groupName=${project.groupName}.core.common
project.core.common.version=${project.version}
project.core.domain.groupName=${project.groupName}.core.domain
project.core.domain.version=${project.version}
project.core.logging.groupName=${project.groupName}.core.logging
project.core.logging.version=${project.version}
project.core.adb.groupName=${project.groupName}.core.adb
project.core.adb.version=${project.version}