[versions]
kotlin = "2.2.10"
kotlin-ksp = "2.2.10-2.0.2"
coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlin-inject = "0.9.0"
jna = "5.14.0"
flatlaf = "3.6"
jetbrains-compose = "1.10.0"
compose-compiler = "2.2.10"
log4j = "2.25.4"
lyricist = "1.7.0"
lyricist-processor = "1.7.0"
betterandroid-compose-extension = "1.0.2"
kavaref-core = "1.0.2"
kavaref-extension = "1.0.2"
jbr-api = "1.9.0"
jewel = "0.34.0-253.32098.37"
intellij-platform-icons = "253.31033.145"
junit = "4.13.1"
git-properties = "2.5.7"
zxing = "3.5.4"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }
git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "git-properties" }

[libraries]
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
jna-platform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jna" }
flatlaf = { group = "com.formdev", name = "flatlaf", version.ref = "flatlaf" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-inject-compiler-ksp = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "kotlin-inject" }
kotlin-inject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlin-inject" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
lyricist = { group = "cafe.adriel.lyricist", name = "lyricist", version.ref = "lyricist" }
lyricist-processor = { group = "cafe.adriel.lyricist", name = "lyricist-processor", version.ref = "lyricist-processor" }
betterandroid-compose-extension-desktop = { group = "com.highcapable.betterandroid", name = "compose-extension-desktop", version.ref = "betterandroid-compose-extension" }
kavaref-core = { group = "com.highcapable.kavaref", name = "kavaref-core", version.ref = "kavaref-core" }
kavaref-extension = { group = "com.highcapable.kavaref", name = "kavaref-extension", version.ref = "kavaref-extension" }
jbr-api = { group = "org.jetbrains.runtime", name = "jbr-api", version.ref = "jbr-api" }
jewel-int-ui-standalone = { group = "org.jetbrains.jewel", name = "jewel-int-ui-standalone", version.ref = "jewel" }
intellij-platform-icons = { group = "com.jetbrains.intellij.platform", name = "icons", version.ref = "intellij-platform-icons" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }